// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/on dojo/_base/lang dojo/_base/array esri/geometry/geometryEngine jimu/utils jimu/DataSourceManager jimu/statisticsUtils".split(" "),function(k,g,h,m,n,p,q){return{getClientFeaturesFromMap:function(a,b,f,d){var c=[],c=f?0<b.getSelectedFeatures().length?b.getSelectedFeatures():b.graphics:b.graphics;d&&(c=this._filterFeaturesByExtent(a.extent,c));if(0<c.length){var e=n.getObjectIdField(b);e&&(a=c[0])&&a.attributes&&a.attributes.hasOwnProperty(e)&&c.sort(function(a,b){a.attributes||(a.attributes=
{});b.attributes||(b.attributes={});var c=a.attributes[e],d=b.attributes[e];return c<d?-1:c>d?1:0})}return c},listenClientFeaturesFromMap:function(a,b,f,d,c){var e=[];f&&(e.push(k(b,"selection-complete",g.hitch(this,function(){c(this.getClientFeaturesFromMap(a,b,f,d))}))),e.push(k(b,"selection-clear",g.hitch(this,function(){c(this.getClientFeaturesFromMap(a,b,f,d))}))));d&&e.push(k(a,"extent-change",g.hitch(this,function(){0<b.graphics.length&&c(this.getClientFeaturesFromMap(a,b,f,d))})));e.push(k(b,
"update-end",g.hitch(this,function(){c(this.getClientFeaturesFromMap(a,b,f,d))})));c(this.getClientFeaturesFromMap(a,b,f,d));return{remove:function(){e&&h.forEach(e,g.hitch(this,function(a){a.remove()}));e=null}}},getVaildIndicator:function(a,b,f){var d=[];b.map(g.hitch(this,function(b){(b=this._handleOperator(b,a,f))&&d.push(b)}));if(0<d.length)return d[d.length-1]},getSingleValueFromFeatures:function(a,b,f){var d=p.getInstance(),c=0;if("Features"===a.type){if("DATA_SOURCE_FEATURE_LAYER_FROM_MAP"===
b.dataSourceType||"Features"===d.getDataSourceConfig(b.frameWorkDsId).type)return f.length;c=0;h.forEach(f,function(a){c+=a.attributes.count});return c}if("DATA_SOURCE_FEATURE_LAYER_FROM_MAP"===b.dataSourceType||"Features"===d.getDataSourceConfig(b.frameWorkDsId).type)return this._getStatsFromFeatures(f,a.fieldName,a.statisticsType);var e=0,l=0,c=0;h.forEach(f,function(b){var d=b.attributes[a.fieldName+"_"+a.statisticsType];switch(a.statisticsType){case "sum":e+=d;break;case "min":e=Math.min(e,d);
break;case "max":e=Math.max(e,d);break;case "avg":l+=b.attributes[a.fieldName+"_sum"],c+=b.attributes.count}});"avg"===a.statisticsType&&(e=0===c?0:l/c);return e},filterFeaturesByDataSourceSetting:function(a,b,f){if(0===a.length)return[];if(b.useSelection){var d=a[0].getLayer();if(d){var c=d.getSelectedFeatures();0<c.length&&(a=h.filter(a,function(a){return-1<c.indexOf(a)}))}}b.filterByExtent&&(a=this._filterFeaturesByExtent(f.extent,a));return a},_getStatsFromFeatures:function(a,b,f){return q.getStatisticsResultFromClientSync({featureSet:{features:a},
fieldName:b,statisticTypes:[f]})[f+"Field"]},_filterFeaturesByExtent:function(a,b){var f=a.normalize();return b=h.filter(b,g.hitch(this,function(a){try{if(a.geometry){var b="point"===a.geometry.type||"multipoint"===a.geometry;return h.some(f,g.hitch(this,function(c){return b?c.contains(a.geometry):m.intersects(c,a.geometry)}))}}catch(e){console.error(e)}return!1}))},_handleOperator:function(a,b,f){function d(a){c={};a.valueColor&&(c.valueColor=a.valueColor);a.gaugeColor&&(c.gaugeColor=a.gaugeColor);
a.iconInfo&&(c.iconInfo=a.iconInfo)}var c,e=a.value.map(g.hitch(this,function(b){return a.isRatio?b/100*f:b}));"greater"===a.operator&&b>e[0]?d(a):"smaller"===a.operator&&b<e[0]?d(a):"between"===a.operator&&b>e[0]&&b<e[1]?d(a):"equal"===a.operator&&b===e[0]?d(a):"notEqual"===a.operator&&b!==e[0]&&d(a);return c},isInteger:function(a){return"number"===typeof a&&0===a%1}}});